<?php
/**
 * @var $block \Flekto\Postcode\Block\Customer\Address\Autofill
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div id="block-loader-customer-address" data-role="customer-address-loader" class="loading-mask loading-mask-customer-address">
    <div class="loader">
        <img src="<?= /* @noEscape */ $block->getViewFileUrl('images/loader-1.gif') ?>"
            alt="<?= $escaper->escapeHtml(__('Loading...')) ?>" style="position: absolute;">
    </div>
</div>

<script>
    {
        document.querySelector('#form-validate').appendChild(document.getElementById('block-loader-customer-address'));
    }
</script>

<div class="fieldset address-autofill-fieldset" data-bind="scope: 'address_autofill'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "#block-loader-customer-address": {
            "Flekto_Postcode/js/block-loader": {}
        },
        ".address-autofill-fieldset": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout();?>
        }
    }
</script>
