<?php
$apiHelper = $this->helper('Flekto\Postcode\Helper\ApiClientHelper');
?>
<div class="postcode-results"></div>
<script type="text/javascript">
    require(['jquery', 'Flekto_Postcode/js/postcode_autofill'], function($, postcodenl) {

        $(document).ready(function(e){
            window.checkoutConfig = {};
            window.checkoutConfig.flekto_postcode = {};

            window.checkoutConfig.flekto_postcode.settings = <?php echo json_encode($apiHelper->getJsinit()); ?>;
            window.postcodenlConfig = {
                nlPostcodeInputCloneFrom: "div.zip",
                nlPostcodeInputCloneInsertAfter: "div.country"
            };

            postcodenl.call();
        });
    });
</script>