<?php

$config = $block->getConfig();

?><div class="postcode-eu-status-container">
    <div class="postcode-eu-status-header">
        <h2>Address API</h2>
    </div>

    <div class="postcode-eu-status-content">
        <div class="postcode-eu-status-content-header">
            <p>Module version <strong><?= $block->escapeHtml($config['module_version']) ?></strong></p>

            <?php if ($config['has_credentials']): ?>
                <button type="submit" name="refresh_api_data" value="1" class="action-default scalable button-refresh-api-data"><?= $block->escapeHtml(__('↻ Refresh API data')) ?></button>
            <?php endif ?>
        </div>

        <?php if (!$config['enabled']): ?>
            <div class="message message-warning">Module is disabled via configuration.</div>
        <?php endif ?>

        <?php if (isset($config['account_status'])): ?>
            <h3>API connection</h3>

            <dl class="postcode-eu-api-connection">
                <?php if (isset($block->accountInfo['name'])): ?>
                    <dt>Account name</dt>
                    <dd><?= $block->escapeHtml($block->accountInfo['name']) ?></dd>
                <?php endif ?>
                <dt>Subscription status</dt>
                <dd>
                    <span class="badge-account-status badge-account-status-<?= /* @noEscape */ $config['account_status'] ?>"><?= /* @noEscape */ $block->getApiStatusDescription() ?></span>

                    <?php if (isset($block->accountInfo['subscription'])): ?>
                        <?php
                            $limit = $block->accountInfo['subscription']['limit'];
                            $usage = $block->accountInfo['subscription']['usage'];
                            $usage_percent = round($usage / $limit * 100, 1);
                            $low = round($limit * .75, 2);
                            $high = round($limit * .9, 2);
                        ?>
                            <meter class="accont-usage-meter" min="0" max="<?= $limit ?>" value="<?= $usage ?>" optimum="0" low="<?= $low ?>" high="<?= $high ?>" title="Usage at <?= $usage_percent ?>%"></meter>
                        <?= $usage . ' / ' . $limit ?> euro
                    <?php endif ?>
                </dd>
            </dl>

            <h3>Supported countries</h3>

            <ul class="postcode-eu-supported-countries-list">
                <?php foreach ($config['supported_countries'] as $country): ?>
                    <li><?= /* @noEscape */ $country->name ?></li>
                <?php endforeach ?>
            </ul>
        <?php endif ?>
    </div>
</div>
