<?php

/**
 * @var \PostcodeEu\AddressValidation\Block\System\Config\Status $block
 * @var \Magento\Framework\Escaper $escaper
 */
$config = $block->getConfig();
$accountInfo = $block->getAccountInfo();
$moduleInfo = $block->getModuleInfo();

?><div class="postcode-eu-status-container">
    <div class="postcode-eu-status-header">
        <h2><?= $escaper->escapeHtml(__('Address Validation')) ?></h2>
    </div>

    <div class="postcode-eu-status-content">
        <div class="postcode-eu-status-content-header">
            <p>
                <?= $escaper->escapeHtml(__('Module version')) ?>
                <strong><?= $escaper->escapeHtml($moduleInfo['version']) ?></strong>
                <?php if ($moduleInfo['has_update']): ?>
                <span class="update-available-message">
                    ↻ <a href="<?= $escaper->escapeHtmlAttr($moduleInfo['release_url']) ?>"
                        title="<?= $escaper->escapeHtmlAttr(__('Please update to version %1', [$moduleInfo['latest_version']])) ?>">
                         <?= $escaper->escapeHtml(__('update available')) ?>
                    </a>
                </span>
                <?php endif ?>
            </p>

            <?php if ($config['has_credentials']): ?>
                <button type="submit"
                    name="refresh_api_data"
                    value="1"
                    class="action-default scalable button-refresh-api-data">
                    <?= $escaper->escapeHtml(__('↻ Refresh API data')) ?>
                </button>
            <?php endif ?>
        </div>

        <?php if (!$config['enabled']): ?>
            <div class="message message-warning">
                <?= $escaper->escapeHtml(__('Module is disabled via configuration.')) ?>
            </div>
        <?php endif ?>

        <?php if (isset($config['account_status'])): ?>
            <h3><?= $escaper->escapeHtml(__('API connection')) ?></h3>

            <dl class="postcode-eu-api-connection">
                <?php if (isset($accountInfo['name'])): ?>
                    <dt><?= $escaper->escapeHtml(__('Account name')) ?></dt>
                    <dd><?= $escaper->escapeHtml($accountInfo['name']) ?></dd>
                <?php endif ?>
                <dt><?= $escaper->escapeHtml(__('Subscription status')) ?></dt>
                <dd>
                    <span class="badge-account-status badge-account-status-<?= /* @noEscape */ $config['account_status'] ?>">
                        <?= /* @noEscape */ $block->getApiStatusDescription() ?>
                    </span>

                    <?php if (isset($accountInfo['subscription'])): ?>
                        <?php
                            $limit = $accountInfo['subscription']['limit'];
                            $usage = $accountInfo['subscription']['usage'];
                            $usage_percent = round($usage / $limit * 100, 1);
                            $low = round($limit * .75, 2);
                            $high = round($limit * .9, 2);
                        ?>
                        <meter class="account-usage-meter"
                            min="0"
                            max="<?= /* @noEscape */ $limit ?>"
                            value="<?= /* @noEscape */ $usage ?>"
                            optimum="0"
                            low="<?= /* @noEscape */ $low ?>"
                            high="<?= /* @noEscape */ $high ?>"
                            title="<?= $escaper->escapeHtmlAttr(__('Usage at %1%', [$usage_percent])) ?>"></meter>
                        <?= /* @noEscape */ $usage . ' / ' . /* @noEscape */ $limit ?>
                        <?= $escaper->escapeHtml(__('euro')) ?>
                    <?php endif ?>
                </dd>
            </dl>

            <?php if (!$block->isStatusActive()): ?>
                <div class="message message-notice">
                    <?= $escaper->escapeHtml($block->getApiStatusHint()) ?>
                </div>
            <?php endif ?>

            <h3><?= $escaper->escapeHtml(__('Supported countries')) ?></h3>

            <ul class="postcode-eu-supported-countries-list">
                <?php foreach ($config['supported_countries'] as $name): ?>
                    <li><?= $escaper->escapeHtml($name) ?></li>
                <?php endforeach ?>
            </ul>
        <?php endif ?>
    </div>
</div>
